Переименовать пакет и CLI в mors

diff --git a/opt/bin/libs/debug b/opt/bin/libs/debug
--- a/opt/bin/libs/debug
+++ b/opt/bin/libs/debug
@@ -1,10 +1,10 @@
 #!/bin/sh
 #------------------------------------------------------------------------------
-#	ПАКЕТ КВАС
+#	ПАКЕТ МОРС
 #------------------------------------------------------------------------------
 #
 #	Данный файл содержит функции для отладки и выявления проблем
-#	в работе пакета КВАС
+#	в работе пакета МОРС
 #
 # ------------------------------------------------------------------------------
 #	Разработчик: mail@zeleza.ru
@@ -12,7 +12,7 @@
 #	Лицензия: Apache License 2.0
 # ------------------------------------------------------------------------------------------
 
-. /opt/apps/kvas/bin/libs/main
+. /opt/apps/mors/bin/libs/main
 
 IP_MYIP2='81.90.181.105'
 IP_IFCONFIG='34.160.111.145'
@@ -137,22 +137,22 @@ shadowsocks_debug() {
 #	 Формируем лог отладочной информации
 #
 # ------------------------------------------------------------------------------------------
-kvas__show_list() {
-	if ! [ -f "${KVAS_LIST_FILE}" ] ; then
-		error "Не найден файл списка ${KVAS_LIST_FILE}"
+mors__show_list() {
+	if ! [ -f "${MORS_LIST_FILE}" ] ; then
+		error "Не найден файл списка ${MORS_LIST_FILE}"
 		return
 	fi
 
-	ready 'Количество записей' && when_ok "$(wc -l < ${KVAS_LIST_FILE})"
+	ready 'Количество записей' && when_ok "$(wc -l < ${MORS_LIST_FILE})"
 
-	if grep -Fq 'myip2.ru' "${KVAS_LIST_FILE}" ; then
+	if grep -Fq 'myip2.ru' "${MORS_LIST_FILE}" ; then
 		output='есть'
 	else
 		output='нет'
 	fi
 	ready 'myip2.ru' && when_ok "${output}"
 
-	if grep -Fq 'ifconfig.me' "${KVAS_LIST_FILE}" ; then
+	if grep -Fq 'ifconfig.me' "${MORS_LIST_FILE}" ; then
 		output='есть'
 	else
 		output='нет'
@@ -163,21 +163,21 @@ kvas__show_list() {
 	local count
 	local output
 
-	count=$(grep -Evc -- "${IP_FILTER}" "${KVAS_LIST_FILE}")
+	count=$(grep -Evc -- "${IP_FILTER}" "${MORS_LIST_FILE}")
 	if [ "$count" -eq 0 ]; then
 		output='Не используются домены.'
 	else
-		output=$(grep -Ev -- "${IP_FILTER}" "${KVAS_LIST_FILE}" | grep -vE "${DOMAINS_EXCLUDE}" | head -n 6)
+		output=$(grep -Ev -- "${IP_FILTER}" "${MORS_LIST_FILE}" | grep -vE "${DOMAINS_EXCLUDE}" | head -n 6)
 
 		count="${count}:"
 	fi
 	echo_debug "Доменов ${count}" "${output}"
 
-	count=$(grep -Ec -- "${IP_FILTER}" "${KVAS_LIST_FILE}")
+	count=$(grep -Ec -- "${IP_FILTER}" "${MORS_LIST_FILE}")
 	if [ "$count" -eq 0 ]; then
 		output='Не используются IP или диапазоны.'
 	else
-		output=$(grep -E -- "${IP_FILTER}" "${KVAS_LIST_FILE}" | head -n 6)
+		output=$(grep -E -- "${IP_FILTER}" "${MORS_LIST_FILE}" | head -n 6)
 
 		count="${count}:"
 	fi
@@ -228,7 +228,7 @@ iptables__text_empty() {
 
 	# если вызывается как один из дебагов, то можно передать silent/short
 	if [ -z "${2}" ] ; then
-		echo 'Сообщите об этом https://t.me/kvas_pro и вызовите kvas reset'
+		echo 'Сообщите об этом https://t.me/mors_pro и вызовите mors reset'
 	fi
 }
 
@@ -487,7 +487,7 @@ cmd_ipset_flush() {
 	echo -n 'Заполнение IPSet IP из списка..'
 	local count=0
 	IFS=$'\n'
-	for ip_or_range in $(grep -E -- "$(get_regexp_ip_or_range)" '/opt/etc/kvas.list'); do
+	for ip_or_range in $(grep -E -- "$(get_regexp_ip_or_range)" '/opt/etc/mors.list'); do
 		/opt/sbin/ipset -exist add "${IPSET_TABLE_NAME}" "${ip_or_range}" timeout 0
 
 		count=$((count + 1))
@@ -501,7 +501,7 @@ cmd_ipset_flush() {
 	echo 'На ПК запустите cmd от администратора и выполните там ipconfig /flushdns'
 	echo 'После этого перезапустите командную строку и браузер.'
 	echo 'В командной строке введите nslookup myip2.ru'
-	echo 'Проверьте заполнение списка через kvas ipset'
+	echo 'Проверьте заполнение списка через mors ipset'
 	echo
 }
 
@@ -541,7 +541,7 @@ cmd_ipset_add() {
 
 cmd_ipset_refill() {
 	echo -n 'Переобход списка..'
-	. /opt/apps/kvas/bin/main/ipset_domain
+	. /opt/apps/mors/bin/main/ipset_domain
 	echo 'сделано.'
 
 	echo
@@ -595,15 +595,15 @@ cmd_ipset() {
 	if [ -z "${cached}" ]; then
 		local count='0'
 
-		output='Или не приходило ещё ни одного DNS-запроса о доменах из kvas list;\nили ошибки в конфигурации DNS'
+		output='Или не приходило ещё ни одного DNS-запроса о доменах из mors list;\nили ошибки в конфигурации DNS'
 		if [ -z "${2}" ] ; then
 			# если вызывается как один из дебагов, то можно передать silent/short
-			output="${output}, вызовите kvas debug dns"
+			output="${output}, вызовите mors debug dns"
 		fi
 		output="${output}"';\nили проблема с перехватом DNS'
 		if [ -z "${2}" ] ; then
 			# если вызывается как один из дебагов, то можно передать silent/short
-			output="${output}, вызовите kvas debug iptables"
+			output="${output}, вызовите mors debug iptables"
 		fi
 		output="${output}."
 	else
@@ -623,15 +623,15 @@ cmd_ipset() {
 
 	count=$(/opt/sbin/ipset list "${IPSET_TABLE_NAME}" | grep -F 'timeout 0' | wc -l)
 	if [ "$count" -eq 0 ]; then
-		if grep -Eq -- "${IP_FILTER}" "${KVAS_LIST_FILE}"; then
-			output='Или нет корректных IP, диапазонов в kvas list;\nили проблема с их переносом'
+		if grep -Eq -- "${IP_FILTER}" "${MORS_LIST_FILE}"; then
+			output='Или нет корректных IP, диапазонов в mors list;\nили проблема с их переносом'
 			if [ -z "${2}" ] ; then
 				# если вызывается как один из дебагов, то можно передать silent/short
-				output="${output}, вызовите kvas ipset clear"
+				output="${output}, вызовите mors ipset clear"
 			fi
 			output="${output}."
 		else
-			output='Не используются IP или диапазоны в kvas list.'
+			output='Не используются IP или диапазоны в mors list.'
 		fi
 
 		cached=''
@@ -648,14 +648,14 @@ cmd_ipset() {
 #	 Проверка наличия ip адресов хостов в таблице ipset
 #
 # ------------------------------------------------------------------------------------------
-kvas_list_ipset_check(){
+mors_list_ipset_check(){
 
 	echo "Проверка наличия ip адресов хостов в таблице ipset"
 
 	HAS_NO_ADDRESS=;NOT_IN_TABLE=;
 	sleep 2
 	local bad_ipset_list=""
-	if [ -f "${KVAS_LIST_FILE}" ]; then
+	if [ -f "${MORS_LIST_FILE}" ]; then
 		result_ipset=$(ipset list ${IPSET_TABLE_NAME} | grep -vEi '^[a-z]' | sort )
 		if [ -n "${result_ipset}" ]; then
 			while read -r line || [ -n "${line}" ]; do
@@ -694,7 +694,7 @@ kvas_list_ipset_check(){
 
 				fi
 				
-			done < "${KVAS_LIST_FILE}"
+			done < "${MORS_LIST_FILE}"
 
 			# Удаляем пустые строки
 			bad_ipset_list=$(printf "%s" "${bad_ipset_list}" | sed '/^$/d')
@@ -710,11 +710,11 @@ kvas_list_ipset_check(){
 
 		else
 			error "Таблица защиты ${IPSET_TABLE_NAME} отсутствует в списке ipset"
-			echo -e "Проверьте работу скрипта ${GREN}/opt/apps/kvas/bin/main/ipset${NOCL}, запустив его."
+			echo -e "Проверьте работу скрипта ${GREN}/opt/apps/mors/bin/main/ipset${NOCL}, запустив его."
 		fi
 	else
-		error "Отсутствует защищенный список /opt/etc/kvas.list"
-		echo -e "Добавьте домены в этот список командой ${GREN}kvas add <domain.ru>${NOCL}"
+		error "Отсутствует защищенный список /opt/etc/mors.list"
+		echo -e "Добавьте домены в этот список командой ${GREN}mors add <domain.ru>${NOCL}"
 	fi
 
 	[ "${HAS_NO_ADDRESS}" = true ] && {
@@ -751,10 +751,10 @@ kvas_list_ipset_check(){
 #	 Формируем лог отладочной информации
 #
 # ------------------------------------------------------------------------------------------
-kvas_adguard_debug() {
+mors_adguard_debug() {
 
-#	result=$(cat < "/opt/apps/kvas/bin/main/adguard" | sed 's/^\(.*\)\(#.*\)/\2/; /^#/d; /^$/d')
-#	echo_debug "Скрипт заполнения защищенный список /opt/apps/kvas/bin/main/dnsmasq" "${result}"
+#	result=$(cat < "/opt/apps/mors/bin/main/adguard" | sed 's/^\(.*\)\(#.*\)/\2/; /^#/d; /^$/d')
+#	echo_debug "Скрипт заполнения защищенный список /opt/apps/mors/bin/main/dnsmasq" "${result}"
 	result=$(cat < "${ADGUARD_IPSET_FILE}" | sed 's/^\(.*\)\(#.*\)/\2/; /^#/d; /^$/d' | sed -e '$d' | sed 's/^...../*****/' )
 	echo_debug "Блок записей по ipset в ${ADGUARD_IPSET_FILE}" "${result}"
 	
@@ -771,8 +771,8 @@ kvas_adguard_debug() {
 adblock_dnsmasq_debug() {
 
 	if [ -n "$(cat < '/opt/etc/dnsmasq.conf' | sed '/^$/d' | sed 's/^\(.*\)\(#.*\)/\2/; /^#/d; /^$/d' | grep "adblock.dnsmasq")" ]; then
-#		result=$(cat < "/opt/apps/kvas/bin/main/adblock")
-#		echo_debug "Скрипт заполнения списка блокировки рекламы/opt/apps/kvas/bin/main/adblock" "${result}"
+#		result=$(cat < "/opt/apps/mors/bin/main/adblock")
+#		echo_debug "Скрипт заполнения списка блокировки рекламы/opt/apps/mors/bin/main/adblock" "${result}"
 		result=$(cat < '/opt/etc/adblock.dnsmasq' | sed -e '/^#/d; /^$/d' )
 		echo_debug "Список блокировки рекламы /opt/etc/adblock.dnsmasq (все записи)" "${result}"
 	fi
@@ -868,7 +868,7 @@ syslog__show() {
 #
 # ------------------------------------------------------------------------------------------
 ping_debug() {
-	#  host=$(cat < '"${KVAS_LIST_FILE}"' | sed 's/^\(.*\)\(#.*\)/\2/; /^#/d; /^$/d' | tr -s '\n' | head -1)
+	#  host=$(cat < '"${MORS_LIST_FILE}"' | sed 's/^\(.*\)\(#.*\)/\2/; /^#/d; /^$/d' | tr -s '\n' | head -1)
 	host='myip2.ru'
 	result=$(ping -c3 "${host}")
 	echo_debug "Прозвон ${host}" "${result}"
@@ -900,11 +900,11 @@ router_info() {
 	ready 'Версия KeenOS' && when_ok $(echo "${info_cache}" | jq -r '.title // empty')
 }
 
-kvas__show_config() {
-	cat < "${KVAS_CONF_FILE}" | grep -v '=$' | grep -v '^$'
+mors__show_config() {
+	cat < "${MORS_CONF_FILE}" | grep -v '=$' | grep -v '^$'
 }
 
-kvas__show_install_log() {
+mors__show_install_log() {
 	if ! [ -f "${INSTALL_LOG}" ] ; then
 		return
 	fi
@@ -923,7 +923,7 @@ kvas__show_install_log() {
 # ------------------------------------------------------------------------------------------
 
 show_guest_nets(){
-	list=$(cat <  "${KVAS_CONF_FILE}" | sed -n 's/INFACE_GUEST_ENT=\(.*\)/\1/p;'| sed 's/[ ]//g; s/^\,//')
+	list=$(cat <  "${MORS_CONF_FILE}" | sed -n 's/INFACE_GUEST_ENT=\(.*\)/\1/p;'| sed 's/[ ]//g; s/^\,//')
 	[ -n "${list}" ] && {
 		ready "Список гостевых сетей"
 		when_ok "${list}"
@@ -931,7 +931,7 @@ show_guest_nets(){
 }
 
 show_services_status(){
-	. /opt/apps/kvas/bin/libs/vpn
+	. /opt/apps/mors/bin/libs/vpn
 	cmd_vpn_status
 	cmd_ads_status
 	if [ -f "${ADGUARDHOME_DEMON}" ] && cmd_adguardhome_status | grep -q ВКЛЮЧЕН ; then
@@ -965,45 +965,45 @@ print_debug() {
 	print_line
 	router_info
 	echo
-	syslog__show 'info'  '!КВАС' 'Последние информационные сообщения [kvas syslog info]:' 20
-	syslog__show 'error' '!КВАС' 'Последние ошибки [kvas syslog error]:'                  20
+	syslog__show 'info'  '!МОРС' 'Последние информационные сообщения [mors syslog info]:' 20
+	syslog__show 'error' '!МОРС' 'Последние ошибки [mors syslog error]:'                  20
 
 	print_line
-	echo -e " ${BLUE}КВАС${NOCL}"
+	echo -e " ${BLUE}МОРС${NOCL}"
 	print_line
-	kvas__show_config
+	mors__show_config
 	echo
-	kvas__show_install_log
-	syslog__show 'info'  'КВАС' 'Последние информационные сообщения [kvas log info]:' 20
-	syslog__show 'error' 'КВАС' 'Последние ошибки [kvas log error]:'                  20
+	mors__show_install_log
+	syslog__show 'info'  'МОРС' 'Последние информационные сообщения [mors log info]:' 20
+	syslog__show 'error' 'МОРС' 'Последние ошибки [mors log error]:'                  20
 
 	print_line
-	echo -e " ${BLUE}Сетевые правила [kvas debug iptables]${NOCL}"
+	echo -e " ${BLUE}Сетевые правила [mors debug iptables]${NOCL}"
 	print_line
 	cmd_debug_iptables
 
 	print_line
-	echo -e " ${BLUE}DNS-сервера [kvas debug dns]${NOCL}"
+	echo -e " ${BLUE}DNS-сервера [mors debug dns]${NOCL}"
 	print_line
 	cmd_debug_dns
 
 	print_line
-	echo -e " ${BLUE}Список пользователя [kvas list]${NOCL}"
+	echo -e " ${BLUE}Список пользователя [mors list]${NOCL}"
 	print_line
-	kvas__show_list
+	mors__show_list
 
 	print_line
-	echo -e " ${BLUE}Список IP для попадания в тоннель [kvas ipset]${NOCL}"
+	echo -e " ${BLUE}Список IP для попадания в тоннель [mors ipset]${NOCL}"
 	print_line
 	cmd_ipset
 
 	print_line
-	echo -e " ${BLUE}Подключения [kvas tunnel]${NOCL}"
+	echo -e " ${BLUE}Подключения [mors tunnel]${NOCL}"
 	print_line
 	cmd_tunnel
 
 	print_line
-	echo -e " ${BLUE}Маршрутизация [kvas route]${NOCL}"
+	echo -e " ${BLUE}Маршрутизация [mors route]${NOCL}"
 	print_line
 	cmd_route 'short'
 }
